F-Droid workflow fixes (#12)

diff --git a/.github/workflows/fdroid.yml b/.github/workflows/fdroid.yml
--- a/.github/workflows/fdroid.yml
+++ b/.github/workflows/fdroid.yml
@@ -4,6 +4,13 @@ name: Generate F-Droid repo
 
 on:
   workflow_dispatch:
+    inputs:
+      dry-run:
+        description: "Skips pushing changes when enabled. Optional. Defaults to false."
+        type: boolean
+        default: false
+        required: false
+
   schedule:
     - cron: "45 2 * * *"
 
@@ -18,7 +25,6 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
 
-
       - name: Create basic directory structure
         run: mkdir -p fdroid/repo
 
@@ -28,16 +34,10 @@ jobs:
 
           git restore-mtime
 
-      - name: Install F-Droid server software
-        run: |
-         sudo add-apt-repository ppa:fdroid/fdroidserver
-         sudo apt-get update
-         sudo apt-get install fdroidserver
-
       - name: Login to Azure - CI Subscription
         uses: Azure/login@6c251865b4e6290e7b78be643ea2d005bc51f69a # v2.1.1
         with:
-          cred: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
+          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
 
       - name: Retrieve secrets
         id: retrieve-secrets
@@ -45,8 +45,7 @@ jobs:
         with:
           keyvault: "bitwarden-ci"
           secrets: "github-gpg-private-key,
-          github-gpg-private-key-passphrase,
-          github-pat-bitwarden-devops-mobile-fdroid"
+          github-gpg-private-key-passphrase"
 
       - name: Import GPG key
         uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # v6.1.0
@@ -61,10 +60,34 @@ jobs:
           ACCOUNT_NAME: bitwardenci
           CONTAINER_NAME: mobile
         run: |
-          mkdir -p $HOME/secrets
           az storage blob download --account-name $ACCOUNT_NAME --container-name $CONTAINER_NAME \
-          --name store_fdroid-keystore.jks fdroid/keystore.p12 --output none \
+          --name fdroid_repo_keystore.jks --file fdroid/keystore.p12 --output none
+          
+          az storage blob download --account-name $ACCOUNT_NAME --container-name $CONTAINER_NAME \
           --name fdroid-config.yml --file fdroid/config.yml --output none
+
+      - name: Validate secrets
+        run: |
+          if [ -f "fdroid/config.yml" ]; then
+            echo "config found. setting permission to 0600"
+            chmod 0600 fdroid/config.yml
+          else
+            echo "config not found!"
+            exit 1
+          fi
+          
+          if [ -f "fdroid/keystore.p12" ]; then
+            echo "keystore found"
+          else
+            echo "keystore not found!"
+            exit 1
+          fi
+          
+      - name: Install F-Droid server software
+        run: |
+         sudo add-apt-repository ppa:fdroid/fdroidserver
+         sudo apt-get update
+         sudo apt-get install fdroidserver
 
       - name: Set up Go
         uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
@@ -72,7 +95,7 @@ jobs:
           go-version: '^1.17.0'
 
       - name: Run update script
-        run: bash update.sh 2>&1
         env:
           GH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
+        run: |
+          bash update.sh --dry-run ${{ inputs.dry-run }}
